config:
  jwt:
    encryKey: salt
    expire: 21600
    header: token

mybatis:
  type-aliases-package: com.galileo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080

spring:
  application:
    name: Galileo
  datasource:
    username: root
    password: root
#    username: William
#    password: chenning3.14
    url: jdbc:mysql://localhost:3306/galileo_astronomy_community?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: 127.0.0.1  # 地址
      port: 6379  # 端口号
      database: 0  # 数据库索引（默认为0）
      timeout: 1800000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
          max-idle: 5  # 连接池中最大空闲连接
          min-idle: 0  # 连接池中最小空闲连接
